# Site settings
title: Ehcache
email: tc-oss@softwareag.com
description: Java's most widely used cache.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.ehcache.org" # the base hostname & protocol for your site
twitter_username: ehcache
github_username:  ehcache
linkedin_username: terracotta
facebook_username:  Terracotta


# Build settings
markdown: kramdown


defaults:
  -
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      type: "drafts"
    values:
      layout: "post"
  -
    scope:
      path: "community"
      type: "pages"
    values:
      layout: "community_page"
  -
    scope:
      path: "documentation"
      type: "pages"
    values:
      layout: "docs_page"
